import './globals.css';

import { Poppins, Roboto } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '800'],
  subsets: ['latin']
});

export const metadata = {
  title: 'HotPizza',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-backgroud text-text">{children}</body>
    </html>
  );
}
