import { Header } from '@/components/Header';
import { CartProvider } from '@/contexts/CartContext';
import { Roboto_Flex as Roboto } from 'next/font/google';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
  preload: true
});

export const metadata = {
  title: 'HotPizza',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.className} bg-backgroud text-text`}>
        <CartProvider>
          <Header />

          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
